---
trigger: 
  - master
pool: 
  name: default
steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: restore
      projects: src/NopCommerce.sln
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      projects: src/NopCommerce.sln 